// solid_src_no_virtual/src/components/Scheduler/TimelineGrid.tsx
import { For, Show, createEffect, type Component, type JSX } from 'solid-js';
import type { Resource, EventItem } from './types';
import { EventCard } from './EventCard';
import { cn } from '../../lib/utils';

interface TimelineGridProps {
  gridRef: (el: HTMLDivElement) => void;
  draggedElementRef: (el: HTMLDivElement) => void;
  draggedGridRowRef: (el: HTMLDivElement) => void;
  dropIndicator: { resourceId: string; startCol: number; endCol: number } | null;
  resizeIndicator: { eventId: string; startCol: number; endCol: number } | null;
  rowDrag: { resourceId: string; currentIndex: number } | null;
  rowDropIndicator: number | null;
  isPanning: boolean;
  onMouseDown: (e: MouseEvent) => void;
  onMouseMove: (e: MouseEvent) => void;
  onMouseUpOrLeave: () => void;
  totalWidth: number;
  hours: number[];
  totalHours: number;
  formatHourLabel: (hour: number) => string;
  resources: Resource[];
  selection: { resourceId: string; startSlot: number; currentSlot: number; } | null;
  totalSlots: number;
  startCardDrag: (e: PointerEvent, eventId: string) => void;
  startCardResize: (e: PointerEvent, eventId: string, direction: 'left' | 'right') => void;
  handleRowPointerDown: (e: PointerEvent, resourceId: string) => void;
  renderEvent?: (event: EventItem, onDragStart?: (e: PointerEvent, eventId: string) => void, onResizeStart?: (e: PointerEvent, eventId: string, direction: 'left' | 'right') => void) => JSX.Element;
  interactionEventId: string | undefined;
  layoutEngine: () => any;
}

export const TimelineGrid: Component<TimelineGridProps> = (props) => {

  const GridRow = (rowProps: { resource: Resource, index: () => number }) => {
    const res = () => rowProps.resource;

    // Reactively binds height to the layout engine
    const height = () => props.layoutEngine().rowHeights[res().id] || 140;

    const resourceEvents = () => props.layoutEngine().eventsByResource[res().id] || [];
    const isDraggingRow = () => props.rowDrag?.resourceId === res().id;
    const isSelectedRow = () => !!(props.selection && props.selection.resourceId === res().id);
    const isDropTargetRow = () => !!(props.dropIndicator && props.dropIndicator.resourceId === res().id);
    const hasActiveCard = () => props.interactionEventId ? resourceEvents().some((e: any) => e.id === props.interactionEventId) : false;

    const startCol = () => isSelectedRow() ? Math.min(props.selection!.startSlot, props.selection!.currentSlot) : 0;
    const endCol = () => isSelectedRow() ? Math.max(props.selection!.startSlot, props.selection!.currentSlot) : 0;
    const bgEvenOdd = () => rowProps.index() % 2 === 0 ? 'var(--row-bg-even)' : 'var(--row-bg-odd)';

    const renderRowContent = (isClone: boolean = false) => (
      <div class="absolute inset-0 grid content-center gap-y-2 px-2 pointer-events-none" style={{ "grid-template-columns": `repeat(${props.totalSlots}, minmax(0, 1fr))` }}>

        <Show when={isSelectedRow() && !isClone}>
          <div
            style={{ "grid-column-start": (startCol() + 1).toString(), "grid-column-end": ((startCol() === endCol() ? startCol() + 4 : endCol()) + 1).toString(), "grid-row-start": "1", "z-index": "20" }}
            class="bg-primary/15 border-2 border-dashed border-primary rounded-lg h-[85px] mx-1 backdrop-blur-[1px]"
          />
        </Show>

        <Show when={isDropTargetRow() && props.dropIndicator && !isClone}>
          <div
            style={{ "grid-column-start": (props.dropIndicator!.startCol + 1).toString(), "grid-column-end": (props.dropIndicator!.endCol + 1).toString(), "grid-row-start": "1", "z-index": "30" }}
            class="bg-primary/20 border-2 border-dashed border-primary rounded-xl h-[85px] mx-1 backdrop-blur-[2px] shadow-sm"
          />
        </Show>

        <For each={resourceEvents()}>
          {(event) => {
            const span = () => props.layoutEngine().eventSpans[event.id] || { gridColumnStart: 1, gridColumnEnd: 1 };
            const lane = () => props.layoutEngine().eventLanes[event.id] || 1;
            const isDraggingThis = () => props.interactionEventId === event.id && props.dropIndicator !== null;
            const isResizingThis = () => props.interactionEventId === event.id && props.resizeIndicator !== null;

            const resizeGhostStart = () => isResizingThis() ? props.resizeIndicator!.startCol + 1 : span().gridColumnStart;
            const resizeGhostEnd = () => isResizingThis() ? props.resizeIndicator!.endCol + 1 : span().gridColumnEnd;

            const assignCardRef = (el: HTMLDivElement) => {
              createEffect(() => {
                if (isDraggingThis() && !isClone && props.draggedElementRef) props.draggedElementRef(el);
              });
            };

            return (
              <>
                <Show when={isResizingThis() && !isClone}>
                  <div
                    style={{ "grid-column-start": resizeGhostStart().toString(), "grid-column-end": resizeGhostEnd().toString(), "grid-row-start": lane().toString(), "z-index": "30" }}
                    class="bg-primary/20 border-2 border-dashed border-primary rounded-xl h-[85px] mx-1 backdrop-blur-[2px] shadow-sm"
                  />
                </Show>

                <div
                  ref={assignCardRef}
                  style={{
                    "grid-column-start": (isResizingThis() ? resizeGhostStart() : span().gridColumnStart).toString(),
                    "grid-column-end": (isResizingThis() ? resizeGhostEnd() : span().gridColumnEnd).toString(),
                    "grid-row-start": lane().toString(),
                    "z-index": (isDraggingThis() || isResizingThis() ? 50 : 10).toString(),
                    transform: (!isDraggingThis() || isClone) ? 'translate3d(0, 0, 0)' : undefined
                  }}
                  class={cn("pointer-events-auto px-1 relative", isDraggingThis() && "opacity-80 !transition-none", isResizingThis() && "!transition-none")}
                >
                  <Show
                    when={props.renderEvent}
                    fallback={
                      <EventCard
                        event={event}
                        resource={res()}
                        isDragging={isDraggingThis()}
                        onDragStart={props.startCardDrag}
                        onResizeStart={props.startCardResize}
                      />
                    }
                  >
                    {props.renderEvent!(event, (e) => props.startCardDrag(e, event.id), (e, _, direction) => props.startCardResize(e, event.id, direction))}
                  </Show>
                </div>
              </>
            );
          }}
        </For>
      </div>
    );

    return (
      <div
        class="relative w-full transition-[height] duration-200"
        style={{
          height: `${height()}px`,
          "z-index": (isDraggingRow() ? 50 : (hasActiveCard() ? 40 : 1)).toString()
        }}
      >
        <div
          onPointerDown={(e) => props.handleRowPointerDown(e, res().id)}
          class={cn(
            "absolute inset-0 border-b border-border flex items-start transition-colors cursor-cell",
            isDraggingRow() ? "opacity-30 bg-muted grayscale" : ""
          )}
          style={{ "background-color": isDraggingRow() ? undefined : bgEvenOdd() }}
        >
          {renderRowContent(false)}
        </div>

        <Show when={isDraggingRow()}>
          <div
            ref={props.draggedGridRowRef}
            class="absolute inset-0 border-b border-border flex items-start opacity-100 border-primary/40 bg-primary/5 shadow-2xl !transition-none pointer-events-none"
            style={{ "background-color": bgEvenOdd(), "z-index": "50" }}
          >
            {renderRowContent(true)}
          </div>
        </Show>

        <Show when={props.rowDropIndicator === rowProps.index() && !isDraggingRow() && props.rowDrag}>
          <div
            class="absolute left-0 right-0 h-0.5 bg-primary z-40 pointer-events-none"
            style={{ top: props.rowDropIndicator! > props.rowDrag!.currentIndex ? '100%' : '0px' }}
          />
        </Show>
      </div>
    );
  };

  return (
    <div
      ref={props.gridRef}
      onMouseDown={props.onMouseDown}
      onMouseMove={props.onMouseMove}
      onMouseUp={props.onMouseUpOrLeave}
      onMouseLeave={props.onMouseUpOrLeave}
      class={cn("flex-1 overflow-x-auto select-none", props.isPanning ? "cursor-grabbing" : "cursor-grab")}
      style={{ "scroll-behavior": props.isPanning ? 'auto' : 'smooth' }}
    >
      <div class="flex flex-col relative" style={{ width: `${props.totalWidth}px`, "min-width": '100%' }}>
        <div class="h-14 border-b border-border flex items-center relative bg-card sticky top-0 z-30">
          <For each={props.hours}>
            {(hour, idx) => (
              <div
                class="absolute text-[14px] font-medium text-text-secondary border-l border-border/50 h-full flex items-center pl-3"
                style={{ left: `${(idx() / props.totalHours) * 100}%`, width: `${(1 / props.totalHours) * 100}%` }}
              >
                {props.formatHourLabel(hour)}
              </div>
            )}
          </For>
        </div>

        <div class="flex flex-col relative">
          <div class="absolute inset-0 pointer-events-none flex z-[0]">
            <For each={props.hours}>
              {(_, idx) => (
                <div class="absolute h-full border-l border-border/40" style={{ left: `${(idx() / props.totalHours) * 100}%` }} />
              )}
            </For>
          </div>

          <div class="flex flex-col relative w-full">
            <For each={props.resources}>
              {(resource, index) => <GridRow resource={resource} index={index} />}
            </For>
          </div>
        </div>
      </div>
    </div>
  );
};

// src/components/Scheduler/TimelineGrid.tsx
import React, { memo } from 'react';
import type { Resource, EventItem } from './types';
import { EventCard } from './EventCard';
import { cn } from '@/lib/utils';
import type { VirtualItem } from '@tanstack/react-virtual';

interface TimelineGridProps {
  gridRef: React.RefObject<HTMLDivElement | null>;
  draggedElementRef: React.RefObject<HTMLDivElement | null>;
  draggedGridRowRef: React.RefObject<HTMLDivElement | null>;
  dropIndicator: { resourceId: string; startCol: number; endCol: number } | null;
  resizeIndicator: { eventId: string; startCol: number; endCol: number } | null;
  rowDrag: { resourceId: string; currentIndex: number } | null;
  rowDropIndicator: number | null;
  isPanning: boolean;
  onMouseDown: (e: React.MouseEvent) => void;
  onMouseMove: (e: React.MouseEvent) => void;
  onMouseUpOrLeave: () => void;
  totalWidth: number;
  hours: number[];
  totalHours: number;
  formatHourLabel: (hour: number) => string;
  resources: Resource[];
  selection: { resourceId: string; startSlot: number; currentSlot: number; } | null;
  totalSlots: number;
  startCardDrag: (e: React.PointerEvent, eventId: string) => void;
  startCardResize: (e: React.PointerEvent, eventId: string, direction: 'left' | 'right') => void;
  handleRowPointerDown: (e: React.PointerEvent, resourceId: string) => void;
  renderEvent?: (event: EventItem, onDragStart?: (e: React.PointerEvent, eventId: string) => void, onResizeStart?: (e: React.PointerEvent, eventId: string, direction: 'left' | 'right') => void) => React.ReactNode;
  interactionEventId: string | undefined;
  virtualRows: VirtualItem[];
  totalSize: number;
  rowHeights: Record<string, number>;
  eventLanes: Record<string, number>;
  eventSpans: Record<string, { gridColumnStart: number; gridColumnEnd: number }>;
  eventsByResource: Record<string, EventItem[]>;
}

export const TimelineGrid: React.FC<TimelineGridProps> = memo(({
  gridRef, draggedElementRef, draggedGridRowRef, dropIndicator, resizeIndicator, rowDrag, rowDropIndicator, isPanning,
  onMouseDown, onMouseMove, onMouseUpOrLeave,
  totalWidth, hours, totalHours, formatHourLabel, resources,
  selection, totalSlots,
  startCardDrag, startCardResize, handleRowPointerDown,
  renderEvent, interactionEventId,
  virtualRows, totalSize, rowHeights, eventLanes, eventSpans, eventsByResource,
}) => {
  return (
    <div
      ref={gridRef}
      onMouseDown={onMouseDown} onMouseMove={onMouseMove}
      onMouseUp={onMouseUpOrLeave} onMouseLeave={onMouseUpOrLeave}
      className={cn("flex-1 overflow-x-auto select-none", isPanning ? "cursor-grabbing" : "cursor-grab")}
      style={{ scrollBehavior: isPanning ? 'auto' : 'smooth' }}
    >
      <div className="flex flex-col relative" style={{ width: `${totalWidth}px`, minWidth: '100%' }}>
        {/* Hour Headers Row */}
        <div className="h-14 border-b border-border flex items-center relative bg-card sticky top-0 z-50">
          {hours.map((hour, idx) => (
            <div
              key={hour}
              className="absolute text-[10px] font-semibold text-text-secondary border-l border-border/50 h-full flex items-center pl-3"
              style={{ left: `${(idx / totalHours) * 100}%`, width: `${(1 / totalHours) * 100}%` }}
            >
              {formatHourLabel(hour)}
            </div>
          ))}
        </div>

        {/* Grid Body */}
        <div className="flex flex-col relative">
          <div className="absolute inset-0 pointer-events-none flex z-[0]">
            {hours.map((hour, idx) => (
              <div key={`line-${hour}`} className="absolute h-full border-l border-border/40" style={{ left: `${(idx / totalHours) * 100}%` }} />
            ))}
          </div>

          <div style={{ height: `${totalSize}px`, width: '100%', position: 'relative' }}>
            {virtualRows.map((virtualRow) => {
              const resource = resources[virtualRow.index];
              if (!resource) return null;

              const resourceEvents = eventsByResource[resource.id] || [];

              const isDraggingRow = rowDrag?.resourceId === resource.id;
              const isSelectedRow = selection && selection.resourceId === resource.id;
              const isDropTargetRow = dropIndicator && dropIndicator.resourceId === resource.id;

              // FIXED: Check if the card currently being dragged belongs to THIS specific row
              const hasActiveCard = interactionEventId ? resourceEvents.some(e => e.id === interactionEventId) : false;

              const startCol = isSelectedRow ? Math.min(selection.startSlot, selection.currentSlot) : 0;
              const endCol = isSelectedRow ? Math.max(selection.startSlot, selection.currentSlot) : 0;

              return (
                <div
                  key={`row-${resource.id}`}
                  data-index={virtualRow.index}
                  className="absolute w-full"
                  style={{
                    top: 0, left: 0,
                    height: `${rowHeights[resource.id] || 140}px`,
                    transform: `translateY(${virtualRow.start}px)`,
                    // FIXED: Elevate the ENTIRE ROW's Stacking Context to prevent clipping behind other rows
                    zIndex: isDraggingRow ? 50 : (hasActiveCard ? 40 : 1)
                  }}
                >
                  <div
                    ref={isDraggingRow ? draggedGridRowRef : null}
                    onPointerDown={(e) => handleRowPointerDown(e, resource.id)}
                    className={cn(
                      "border-b border-border absolute w-full h-full flex items-start transition-colors cursor-cell",
                      isDraggingRow && "bg-primary/5 border-primary/20 shadow-xl !transition-none"
                    )}
                    style={{
                      backgroundColor: virtualRow.index % 2 === 0 ? 'var(--row-bg-even)' : 'var(--row-bg-odd)',
                      transform: isDraggingRow ? undefined : 'translate3d(0,0,0)'
                    }}
                  >
                    <div
                      className="absolute inset-0 grid content-center gap-y-2 px-2 pointer-events-none"
                      style={{ gridTemplateColumns: `repeat(${totalSlots}, minmax(0, 1fr))` }}
                    >
                      {/* Slot Selection Box */}
                      {isSelectedRow && (
                        <div
                          style={{ gridColumnStart: startCol + 1, gridColumnEnd: (startCol === endCol ? startCol + 4 : endCol) + 1, gridRowStart: 1, zIndex: 20 }}
                          className="bg-primary/15 border-2 border-dashed border-primary rounded-lg h-[85px] mx-1 backdrop-blur-[1px]"
                        />
                      )}

                      {/* FIXED: Drag Drop Ghost -> Explicit zIndex 30 + Backdrop blur overrides resting cards */}
                      {isDropTargetRow && dropIndicator && (
                        <div
                          style={{ gridColumnStart: dropIndicator.startCol + 1, gridColumnEnd: dropIndicator.endCol + 1, gridRowStart: 1, zIndex: 30 }}
                          className="bg-primary/20 border-2 border-dashed border-primary rounded-xl h-[85px] mx-1 backdrop-blur-[2px] shadow-sm"
                        />
                      )}

                      {resourceEvents.map((event) => {
                        const { gridColumnStart, gridColumnEnd } = eventSpans[event.id] || { gridColumnStart: 1, gridColumnEnd: 1 };
                        const lane = eventLanes[event.id] || 1;

                        const isDraggingThis = interactionEventId === event.id && dropIndicator !== null;
                        const isResizingThis = interactionEventId === event.id && resizeIndicator !== null;

                        const resizeGhostStart = isResizingThis ? resizeIndicator!.startCol + 1 : gridColumnStart;
                        const resizeGhostEnd = isResizingThis ? resizeIndicator!.endCol + 1 : gridColumnEnd;

                        const cardStyle: React.CSSProperties = {
                          gridColumnStart: isResizingThis ? resizeGhostStart : gridColumnStart,
                          gridColumnEnd: isResizingThis ? resizeGhostEnd : gridColumnEnd,
                          gridRowStart: lane,
                          // Resting cards stay at zIndex 10 so ghosts render cleanly above them
                          zIndex: isDraggingThis || isResizingThis ? 50 : 10
                        };
                        if (!isDraggingThis) {
                          cardStyle.transform = 'translate3d(0, 0, 0)';
                        }

                        return (
                          <React.Fragment key={event.id}>

                            {/* FIXED: Resize Ghost -> Explicit zIndex 30 + Backdrop blur */}
                            {isResizingThis && (
                              <div
                                style={{ gridColumnStart: resizeGhostStart, gridColumnEnd: resizeGhostEnd, gridRowStart: lane, zIndex: 30 }}
                                className="bg-primary/20 border-2 border-dashed border-primary rounded-xl h-[85px] mx-1 backdrop-blur-[2px] shadow-sm"
                              />
                            )}

                            <div
                              ref={isDraggingThis ? draggedElementRef : null}
                              style={cardStyle}
                              className={cn(
                                "pointer-events-auto px-1 relative",
                                isDraggingThis && "opacity-80 !transition-none",
                                isResizingThis && "!transition-none"
                              )}
                            >
                              {renderEvent ? (
                                renderEvent(event, (e) => startCardDrag(e, event.id), (e, _, direction) => startCardResize(e, event.id, direction))
                              ) : (
                                <EventCard
                                  event={event}
                                  resource={resource}
                                  isDragging={isDraggingThis}
                                  onDragStart={startCardDrag}
                                  onResizeStart={startCardResize}
                                />
                              )}
                            </div>
                          </React.Fragment>
                        );
                      })}
                    </div>
                  </div>

                  {rowDropIndicator === virtualRow.index && !isDraggingRow && rowDrag && (
                    <div
                      className="absolute left-0 right-0 h-0.5 bg-primary z-40 pointer-events-none"
                      style={{ top: rowDropIndicator > rowDrag.currentIndex ? '100%' : '0px' }}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
});
